name: PHP

on: [ push ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        laravel-version: ['^6.0', '^7.0', '^8.0' ]
        php-version: [ '7.4', '8.0' ]
        exclude:
          - laravel-version: ^6.0
            php-version: 8.0
          - laravel-version: ^7.0
            php-version: 8.0
    name: PHP ${{ matrix.php-version }} on Laravel ${{ matrix.laravel-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xdebug, sqlite
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}"
          composer update --prefer-stable --no-interaction --prefer-dist
      - name: Lint composer.json
        run: composer validate
      - name: Run Tests
        run: composer test:ci
        env:
          CI_TESTING: 'github-actions'
      - name: Upload code coverage
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
